project:
  type: website
  output-dir: docs

website:
  title: "Henry Nadel"
  navbar:
    left:
    - text: Research
      menu: 
        - href: CASA_paper.qmd
          text: "Quantifying Growth: Warehousing in the IE"
        - href: surveillance.qmd
          text: "I.C.E. Surveillance Technologies"
        - href: ISP.qmd
          text: "Nepal's Regional Schooling"
    - text: Data Viz
      menu:
        - href: tidytuesday-1.qmd
          text: "TidyTuesday - Himalayan Mountaineering"
        - href: tidytuesday-2.qmd
          text: "TidyTuesday - Gas Pricing"
        - href: text_analysis.qmd
          text: "Analyzing NYT Headlines"
        - href: sql_project.qmd
          text: "Analyzing Policing with SQL"   
    - text: GIS Mapping
      menu: 
        - href: Warehousing_Corona.qmd
          text: "Warehouses in Corona CA"
    - text: Photography
      menu: 
        - href: nepal_photos.qmd
          text: "Nepal 2025"
    right:
    - icon: github
      href: https://github.com/[your-username]/[your-repo]
      aria-label: GitHub
  page-footer:
    center: "© Henry Nadel, 2025 · Built with Quarto<br>Contact: nadelhenry@gmail.com"
  
format:
  html:
    theme:
      light: minty
    css: styles.css
    toc: false
    page-layout: full