project:
  type: website
  output-dir: docs

website:
  title: "Henry Nadel"
  navbar:
    left:
    - href: index.qmd
      text: "Home"
    - text: Data Viz
      menu:
        - href: tidytuesday-1.qmd
          text: "TidyTuesday - Himalayan Mountaineering"
        - href: tidytuesday-2.qmd
          text: "TidyTuesday - Gas Pricing"
        - href: text_analysis.qmd
          text: "Analysing NYTimes Headlines"
        - href: Permutation_test.qmd
          text: "Permutation Testing"
        - href: sql_project.qmd
          text: "SQL Project"         
    - text: Blog Posts
      menu:
        - href: ethics_blog.qmd
          text: "Predictive Analytics at Target"
    right:
    - icon: github
      href: https://github.com/[your-username]/[your-repo]
      aria-label: GitHub
  page-footer:
    center: "© Henry Nadel, 2025 · Built with Quarto"

  
format:
  html:
    theme:
      light: minty
      dark: slate
    css: styles.css
    toc: false
    page-layout: full